export {default as NavBar} from './NavBar/NavBar'
export {default as Banner} from './Banner/Banner'
export {default as Footer} from './Footer/Footer'
export {default as About} from './About/About'
export {default as Login} from './Login/Login'
export {default as SignUp} from './SignUp/SignUp'
export {default as ChatBot} from './ChatBot/ChatBot'